apiVersion: v1
kind: Service
metadata:
  labels:
    app: thinknyxdemo
  name: thinknyxdemosvc
  namespace: yogeshtestns
spec:
  ports:
  - name: testsvc
    nodePort: 30010
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: thinknyxdemo
  type: NodePort
